version: '3.8'

services:
  redis:
    image: redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mynet
  sidekiq:
    build: .
    command: bundle exec sidekiq 
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - mynet
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["rails", "server", "-b", "0.0.0.0"]
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - mynet
    environment:
      REDIS_URL: redis://redis:6379
networks:
  mynet:
    driver: bridge